name: nae
description: A web cms made with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  flutter_markdown: ^0.3.5
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/posts/post_1.md
    - assets/posts/post_2.md
    - assets/posts/post_3.md
