/// Generated by AssetsRefGenerator on 2020/04/29
class Res {
  static const String post_1 = "assets/posts/post_1.md";
  static const String post_2 = "assets/posts/post_2.md";
  static const String post_3 = "assets/posts/post_3.md";
}
